---
title: "Análisis decesos evolución Covid-19 - Italia, España, Brasil, Corea del Sur (27/03/2020)"
author: "Claudio Bustos"
date: "27/3/2020"
output: html_document
---

```{r setup, include=FALSE}
source("analisis_decesos.R")
knitr::opts_chunk$set(echo = FALSE,warning = FALSE)
library(pander)
datos.decesos.pais<-lapply(datos.decesos.pais,function(x) {x<-x[x$fecha<=43916,]})
```


* Reportes anteriores: https://github.com/clbustos/analisis_covid19_chile


## Análisis de datos observados


```{r}
plot.avance.pais(datos.decesos.pais,predicted = F,min.casos = 10)+theme_bw()+viridis::scale_color_viridis(discrete=TRUE,direction = -1)
```




```{r}
plot.avance.pais(datos.decesos.pais,predicted = T,min.casos = 10, span.param = NULL)+facet_wrap(~pais)

```


```{r}
plot.tasa.casos(datos.decesos.pais,min.casos = 10,span.param = NULL)+
  facet_wrap(~pais)+
  ylim(0.9,2.3)+
    geom_abline(intercept=1.4, slope=0,alpha=0.5,col="darkred")+
  geom_abline(intercept=1.2, slope=0,alpha=0.5,col="orange")+
  geom_abline(intercept=1, slope=0,alpha=0.5,col="darkgreen")+theme_bw()
```


## Predicción


```{r}
prediccion<-prediccion.casos(datos.decesos.pais,min.casos = 10)
plot( prediccion)
```

```{r,results='asis'}
r<-lapply(prediccion$tar2,function(x) {round(tail(x,7)[,c(1,2,3,4)],2)})
formatear_tablas(r, "Tendencia + AR(1)")
```

```{r,results='asis'}
r<-lapply(prediccion$exp, function(x) {round(tail(x,7)[,c(1,2,3,4)],2)})
formatear_tablas(r, "Exponencial")
```

```{r,results='asis'}
r<-lapply(prediccion$arima,function(x) {round(tail(x,7)[,c(1,2,3,4)],2)})
formatear_tablas(r, "ARIMA(1,1,0) con deriva")
```


Fuentes de información:

* Chile: https://www.minsal.cl/nuevo-coronavirus-2019-ncov/casos-confirmados-en-chile-covid-19/.
* Otros países: https://www.worldometers.info/coronavirus/#countries
